/** Names the app's icon vocabulary; callers mark decorative instances aria-hidden. */

export {
  ArrowDown as IncomingIcon,
  ArrowUp as OutgoingIcon,
  Check as CheckIcon,
  CircleAlert as AlertIcon,
  Cloud as RemoteBranchIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsDownUp as CollapseAllIcon,
  ChevronsUpDown as ExpandAllIcon,
  EllipsisVertical as EllipsisIcon,
  ExternalLink as OpenInAppIcon,
  File as FileIcon,
  Folder as FolderIcon,
  GitBranch as BranchIcon,
  Tag as TagIcon,
  GitFork as WorktreeIcon,
  Languages as LanguageIcon,
  Palette as AppearanceIcon,
  PanelsTopLeft as LayoutIcon,
  PanelLeft as SidebarIcon,
  PanelTop as CompanionIcon,
  Plus as PlusIcon,
  Pencil as PencilIcon,
  Power as QuitIcon,
  RotateCw as RefreshIcon,
  RotateCcw as ResetLayoutIcon,
  Search as SearchIcon,
  Trash2 as TrashIcon,
  X as CloseIcon,
} from "lucide-react";
