/** Owns detached Git workers and their foreground children; isolation is not a security sandbox. */
import { spawn, spawnSync } from 'node:child_process';
import { lstat, mkdir, mkdtemp, readFile, readdir, realpath, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { homedir, platform, tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { createServer } from 'node:net';
import { once } from 'node:events';
import { fileURLToPath } from 'node:url';
import { isEntryPoint, parseOptions, readJsonBounded, writeEvidence } from '../../scripts/evidence.mjs';

const STATE = '.verification/worker';
const MODES = ['web', 'native', 'verify'];
const ignoredArtifacts = ['.verification/', 'node_modules/', 'dist/', 'src-tauri/target/', 'src-tauri/gen/', 'src-tauri/permissions/autogenerated/'];

function gitEnvironment(environment = process.env) {
  const isolated = { ...environment };
  for (const key of Object.keys(isolated)) if (key.startsWith('GIT_')) delete isolated[key];
  return isolated;
}

function git(root, args) {
  const result = spawnSync('git', args, { cwd: root, env: gitEnvironment(), encoding: 'utf8', maxBuffer: 2 * 1024 * 1024, windowsHide: true });
  if (result.error || result.status !== 0) throw new Error('git_operation_failed');
  return result.stdout.trim();
}

async function exists(path) {
  try { await lstat(path); return true; }
  catch (error) { if (error.code === 'ENOENT') return false; throw error; }
}

function isWithin(root, path) {
  const child = relative(root, path);
  return child === '' || (!child.startsWith(`..${process.platform === 'win32' ? '\\' : '/'}`) && child !== '..' && !isAbsolute(child));
}

async function repository(root) {
  root = await realpath(root);
  const common = await realpath(git(root, ['rev-parse', '--path-format=absolute', '--git-common-dir']));
  return { root, common, registry: join(common, 'gitview-workers') };
}

function nativeDataDirectory(identifier) {
  if (platform() === 'darwin') return join(homedir(), 'Library', 'Application Support', identifier);
  if (platform() === 'win32') return join(process.env.APPDATA ?? join(homedir(), 'AppData', 'Roaming'), identifier);
  const dataRoot = process.env.XDG_DATA_HOME;
  return join(dataRoot && isAbsolute(dataRoot) ? dataRoot : join(homedir(), '.local', 'share'), identifier);
}

function publicWorker(worker) {
  return { status: 'prepared', id: worker.id, revision: worker.revision, port: worker.port, identifier: worker.identifier, baseline: 'committed_revision_only', dirtyParentEdits: 'not_copied', dependencySetup: 'npm ci inside worker first', isolation: 'not_a_security_sandbox' };
}

/** Creates a fresh detached checkout. Never stages, commits, copies or stashes parent edits. */
export async function prepareWorker({ root = process.cwd(), path, rev, port }) {
  if (!path || !rev || !/^\d+$/.test(String(port)) || Number(port) < 1024 || Number(port) > 65535) throw new Error('invalid_arguments');
  const repo = await repository(root);
  const destination = join(await realpath(dirname(resolve(path))), basename(resolve(path)));
  if (isWithin(repo.root, destination) || isWithin(repo.common, destination)) throw new Error('worker_path_must_be_external');
  if (await exists(destination)) throw new Error('worker_path_exists');
  const revision = git(repo.root, ['rev-parse', '--verify', '--end-of-options', `${rev}^{commit}`]);
  if (!/^[a-f0-9]{40,64}$/.test(revision)) throw new Error('invalid_revision');
  const id = randomBytes(12).toString('hex');
  const identifier = `com.gitview.worker.w${id}`;
  const worker = { schemaVersion: 1, id, root: destination, common: repo.common, revision, port: Number(port), identifier, appData: nativeDataDirectory(identifier) };
  await mkdir(join(repo.registry, 'ports'), { recursive: true, mode: 0o700 });
  const reservation = join(repo.registry, 'ports', `${worker.port}.json`);
  try { await writeFile(reservation, JSON.stringify({ id }), { flag: 'wx', mode: 0o600 }); }
  catch (error) { if (error.code === 'EEXIST') throw new Error('worker_port_reserved'); throw error; }
  let added = false;
  try {
    git(repo.root, ['worktree', 'add', '--detach', '--', destination, revision]);
    added = true;
    if (await exists(join(destination, '.verification'))) throw new Error('worker_state_path_exists');
    const exclude = join(repo.common, 'info', 'exclude');
    await mkdir(dirname(exclude), { recursive: true });
    // Local Git metadata only: the ownership marker must never enter a source commit.
    const current = await readFile(exclude, 'utf8').catch(error => { if (error.code === 'ENOENT') return ''; throw error; });
    if (!current.split('\n').includes('/.verification/')) await writeFile(exclude, `${current}\n/.verification/\n`);
    await writeEvidence(join(destination, STATE), 'ownership.json', worker);
    await writeFile(join(repo.registry, `${id}.json`), `${JSON.stringify(worker)}\n`, { flag: 'wx', mode: 0o600 });
    return worker;
  } catch (error) {
    // Failed setup never force-removes a worktree that acquired user changes.
    if (added) { try { git(repo.root, ['worktree', 'remove', '--', destination]); } catch { throw new Error('worker_setup_failed_checkout_preserved'); } }
    await rm(reservation);
    throw error;
  }
}

async function ownedWorker(root, path) {
  if (!path) throw new Error('invalid_arguments');
  const repo = await repository(root);
  const destination = await realpath(path);
  let worker;
  try { worker = await readJsonBounded(join(destination, STATE, 'ownership.json')); }
  catch { throw new Error('worker_not_owned'); }
  if (await realpath(join(destination, STATE)) !== join(destination, STATE) || (await lstat(join(destination, STATE, 'ownership.json'))).isSymbolicLink()) throw new Error('worker_not_owned');
  if (worker.schemaVersion !== 1 || !/^[a-f0-9]{24}$/.test(worker.id) || worker.root !== destination || worker.common !== repo.common) throw new Error('worker_not_owned');
  const registered = await readJsonBounded(join(repo.registry, `${worker.id}.json`));
  if (JSON.stringify(worker) !== JSON.stringify(registered) || await realpath(git(destination, ['rev-parse', '--path-format=absolute', '--git-common-dir'])) !== repo.common) throw new Error('worker_not_owned');
  const admin = await realpath(git(destination, ['rev-parse', '--absolute-git-dir']));
  if (admin === repo.common || !isWithin(join(repo.common, 'worktrees'), admin)) throw new Error('worker_not_owned');
  return { worker, repo, lock: join(admin, 'gitview-worker-active') };
}

async function ownedNativeData(worker, create = false) {
  const directory = worker.appData;
  const marker = join(directory, '.gitview-worker-owner.json');
  if (!await exists(directory)) {
    if (!create) return false;
    await mkdir(dirname(directory), { recursive: true });
    await mkdir(directory, { mode: 0o700 });
    await writeFile(marker, JSON.stringify({ id: worker.id, common: worker.common }), { flag: 'wx', mode: 0o600 });
  }
  if ((await lstat(directory)).isSymbolicLink() || (await lstat(marker)).isSymbolicLink()) throw new Error('worker_native_data_not_owned');
  const owner = await readJsonBounded(marker);
  if (owner.id !== worker.id || owner.common !== worker.common) throw new Error('worker_native_data_not_owned');
  return true;
}

/** Refuses active, dirty and unowned checkouts; ignored generated build artifacts may be removed. */
export async function removeWorker({ root = process.cwd(), path }) {
  const { worker, repo, lock } = await ownedWorker(root, path);
  if (await exists(lock)) throw new Error('worker_active_or_interrupted');
  try { await mkdir(lock, { mode: 0o700 }); }
  catch (error) { if (error.code === 'EEXIST') throw new Error('worker_active_or_interrupted'); throw error; }
  try {
    if (git(worker.root, ['status', '--porcelain', '--untracked-files=all'])) throw new Error('worker_dirty');
    const unownedIgnored = git(worker.root, ['ls-files', '--others', '--ignored', '--exclude-standard', '-z', '--', '.', ...ignoredArtifacts.map(directory => `:(exclude)${directory.slice(0, -1)}`)]);
    if (unownedIgnored) throw new Error('worker_untracked_files');
    const nativeData = await ownedNativeData(worker);
    git(repo.root, ['worktree', 'remove', '--', worker.root]);
    if (nativeData) await rm(worker.appData, { recursive: true });
    await rm(join(repo.registry, `${worker.id}.json`));
    await rm(join(repo.registry, 'ports', `${worker.port}.json`));
    return { status: 'removed', id: worker.id, nativeData: nativeData ? 'removed_owned_data' : 'not_created' };
  } finally { await rm(lock, { recursive: true, force: true }); }
}

async function assertPortAvailable(port) {
  const server = createServer();
  try {
    server.listen({ host: '127.0.0.1', port, exclusive: true });
    await once(server, 'listening');
  } catch { throw new Error('worker_port_busy'); }
  finally { if (server.listening) await new Promise(done => server.close(done)); }
}

async function refuseRuntimeSymlinks(directory) {
  if (!await exists(directory)) return;
  const metadata = await lstat(directory);
  if (metadata.isSymbolicLink()) throw new Error('worker_runtime_symlink');
  if (!metadata.isDirectory()) return;
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) throw new Error('worker_runtime_symlink');
    if (entry.isDirectory()) await refuseRuntimeSymlinks(join(directory, entry.name));
  }
}

async function configureRuntime(worker, temporary) {
  const state = join(worker.root, STATE);
  const cache = join(state, 'cache');
  for (const path of ['cache', 'target', 'vite.config.mjs', 'tauri.conf.json', 'runtime.json']) {
    const destination = join(state, path);
    await refuseRuntimeSymlinks(destination);
  }
  await mkdir(cache, { recursive: true });
  await writeFile(join(state, 'vite.config.mjs'), `import baseline from '../../vite.config.ts';\nexport default { ...baseline, cacheDir: ${JSON.stringify(join(cache, 'vite'))}, server: { ...baseline.server, headers: { ...baseline.server?.headers, 'X-GitView-Worker': ${JSON.stringify(worker.id)} } } };\n`, { mode: 0o600 });
  const tauri = { identifier: worker.identifier, build: { beforeDevCommand: '', devUrl: `http://127.0.0.1:${worker.port}` } };
  await writeEvidence(state, 'tauri.conf.json', tauri);
  await writeEvidence(state, 'runtime.json', { port: worker.port, identifier: worker.identifier, appData: worker.appData, database: join(worker.appData, 'diagnostics', 'diagnostics.sqlite'), temporary, evidence: state });
  return {
    ...gitEnvironment(),
    CARGO_TARGET_DIR: join(state, 'target'),
    CARGO_HOME: join(cache, 'cargo'),
    npm_config_cache: join(cache, 'npm'),
    XDG_CACHE_HOME: join(cache, 'xdg'),
    ...(platform() !== 'darwin' && platform() !== 'win32' ? { XDG_DATA_HOME: dirname(worker.appData) } : {}),
    TMPDIR: temporary,
  };
}

function childCommand(mode, worker) {
  if (mode === 'web') return ['node_modules/vite/bin/vite.js', '--config', `${STATE}/vite.config.mjs`, '--host', '127.0.0.1', '--port', String(worker.port), '--strictPort'];
  if (mode === 'native') return ['node_modules/@tauri-apps/cli/tauri.js', 'dev', '--config', join(worker.root, STATE, 'tauri.conf.json')];
  if (mode === 'verify') return ['scripts/verify.mjs', '--suite', 'all', '--output', `${STATE}/evidence`];
  throw new Error('invalid_mode');
}

/** The live supervisor pins its process-group identity until cleanup kills that whole group. */
async function supervise(mode) {
  if (!process.send || !MODES.includes(mode)) throw new Error('invalid_arguments');
  const worker = await readJsonBounded(join(process.cwd(), STATE, 'ownership.json'));
  const child = spawn(process.execPath, childCommand(mode, worker), { cwd: worker.root, env: process.env, shell: false, stdio: 'ignore' });
  // Remain alive until the owner kills the group; an early leader exit could orphan descendants.
  process.on('SIGTERM', () => {});
  process.on('SIGINT', () => {});
  process.on('message', () => {});
  child.once('error', () => process.send({ code: 'worker_start_failed', exitCode: null }));
  child.once('close', (exitCode, signal) => process.send({ code: signal ? 'worker_child_signalled' : exitCode === 0 ? 'ok' : 'worker_child_failed', exitCode }));
}

function launch(mode, options, children) {
  const child = spawn(process.execPath, [fileURLToPath(import.meta.url), '--child', mode], { ...options, shell: false, detached: true, stdio: ['ignore', 'ignore', 'ignore', 'ipc'] });
  const entry = { child, finished: false, result: null };
  children.add(entry);
  let complete;
  entry.completed = new Promise(done => { complete = done; });
  child.on('message', result => {
    if (!['ok', 'worker_start_failed', 'worker_child_signalled', 'worker_child_failed'].includes(result?.code)) return;
    entry.result = result;
    complete(result);
  });
  entry.closed = new Promise(done => {
    child.once('error', () => { entry.startFailed = true; });
    child.once('close', () => {
      entry.finished = true;
      entry.result ??= { code: entry.startFailed ? 'worker_start_failed' : 'worker_child_signalled', exitCode: null };
      complete(entry.result);
      done(entry.result);
    });
  });
  return entry;
}

function signalChild(entry, signal) {
  if (entry.finished || !entry.child.pid) return;
  try { process.kill(-entry.child.pid, signal); }
  catch (error) { if (error.code !== 'ESRCH') throw error; }
}

async function stopChildren(children) {
  for (const entry of children) signalChild(entry, 'SIGTERM');
  // Supervisors stay alive through this grace period, so no reused/stale PID is signalled.
  const timer = setTimeout(() => { for (const entry of children) signalChild(entry, 'SIGKILL'); }, 2000);
  try { await Promise.all([...children].map(entry => entry.closed)); }
  finally { clearTimeout(timer); }
}

async function waitForWeb(entry, worker, signal) {
  const deadline = Date.now() + 30000;
  while (Date.now() < deadline && !entry.result && !signal?.aborted) {
    try {
      const response = await fetch(`http://127.0.0.1:${worker.port}`, { signal: AbortSignal.timeout(300) });
      if (response.ok && response.headers.get('X-GitView-Worker') === worker.id) return;
    }
    catch { /* Vite has not bound its strict port yet; child exit remains authoritative. */ }
    await new Promise(done => setTimeout(done, 50));
  }
  throw new Error(signal?.aborted ? 'worker_cancelled' : 'worker_web_not_ready');
}

/** Runs a fixed mode in an owned checkout and reaps all owned children before releasing its lock. */
export async function runWorker({ root = process.cwd(), path, mode, signal, onReady }) {
  if (!MODES.includes(mode)) throw new Error('invalid_mode');
  const { worker, lock } = await ownedWorker(root, path);
  if (platform() === 'win32') throw new Error('worker_lifecycle_requires_posix');
  try { await mkdir(lock, { mode: 0o700 }); }
  catch (error) { if (error.code === 'EEXIST') throw new Error('worker_active_or_interrupted'); throw error; }
  const children = new Set();
  let cancelled = false;
  let stopping;
  let temporary;
  const cancel = () => { cancelled = true; stopping ??= stopChildren(children); };
  signal?.addEventListener('abort', cancel, { once: true });
  try {
    if (signal?.aborted) throw new Error('worker_cancelled');
    await assertPortAvailable(worker.port);
    const temporaryRoot = await realpath(tmpdir());
    const discovered = spawnSync('git', ['rev-parse', '--absolute-git-dir'], { cwd: temporaryRoot, env: gitEnvironment(), encoding: 'utf8', windowsHide: true });
    if (discovered.error) throw new Error('git_operation_failed');
    if (discovered.status === 0) throw new Error('worker_temporary_root_in_repository');
    // Git fixtures must not discover the worker checkout through their temporary parent.
    temporary = await mkdtemp(join(temporaryRoot, `gitview-worker-${worker.id}-`));
    const env = await configureRuntime(worker, temporary);
    if (signal?.aborted) throw new Error('worker_cancelled');
    if (mode === 'native') await ownedNativeData(worker, true);
    if (signal?.aborted) throw new Error('worker_cancelled');
    const options = { cwd: worker.root, env };
    if (mode === 'verify') {
      const child = launch('verify', options, children);
      const result = await child.completed;
      return { status: cancelled ? 'cancelled' : result.code === 'ok' ? 'passed' : 'failed', mode, id: worker.id, code: cancelled ? 'worker_cancelled' : result.code };
    }
    const web = launch('web', options, children);
    await waitForWeb(web, worker, signal);
    onReady?.({ status: 'running', mode, id: worker.id, port: worker.port, identifier: worker.identifier });
    if (mode === 'web') {
      const result = await web.completed;
      return { status: cancelled ? 'cancelled' : result.code === 'ok' ? 'passed' : 'failed', mode, id: worker.id, code: cancelled ? 'worker_cancelled' : result.code };
    }
    if (signal?.aborted) throw new Error('worker_cancelled');
    const native = launch('native', options, children);
    const result = await Promise.race([native.completed, web.completed]);
    return { status: cancelled ? 'cancelled' : result.code === 'ok' ? 'passed' : 'failed', mode, id: worker.id, code: cancelled ? 'worker_cancelled' : result.code };
  } finally {
    signal?.removeEventListener('abort', cancel);
    await (stopping ?? stopChildren(children));
    if (temporary) await rm(temporary, { recursive: true, force: true });
    await rm(lock, { recursive: true });
  }
}

if (isEntryPoint(import.meta.url) && process.argv[2] === '--child') {
  try { await supervise(process.argv[3]); }
  catch { process.exitCode = 1; process.disconnect?.(); }
} else if (isEntryPoint(import.meta.url)) {
  const controller = new AbortController();
  const cancel = () => controller.abort();
  process.on('SIGINT', cancel);
  process.on('SIGTERM', cancel);
  try {
    const [action, ...argv] = process.argv.slice(2);
    const allowed = action === 'prepare' ? ['root', 'path', 'rev', 'port'] : action === 'run' ? ['root', 'path', 'mode'] : ['root', 'path'];
    const options = parseOptions(argv, allowed);
    const result = action === 'prepare' ? publicWorker(await prepareWorker(options)) : action === 'run' ? await runWorker({ ...options, signal: controller.signal, onReady: summary => process.stdout.write(`${JSON.stringify(summary)}\n`) }) : action === 'remove' ? await removeWorker(options) : (() => { throw new Error('invalid_action'); })();
    process.stdout.write(`${JSON.stringify(result)}\n`);
    process.exitCode = ['failed', 'cancelled'].includes(result.status) ? 1 : 0;
  } catch (error) {
    const code = /^[a-z_]+$/.test(error.message) ? error.message : 'worker_operation_failed';
    process.stderr.write(`${JSON.stringify({ status: 'failed', code })}\n`);
    process.exitCode = 1;
  } finally {
    process.removeListener('SIGINT', cancel);
    process.removeListener('SIGTERM', cancel);
  }
}
